# https://taskfile.dev

version: "3"

vars:
  DOCKER_REGISTRY: attap0n
  DOCKER_IMAGE: "cronicle"
  CRONICLE_VERSION:
    sh: curl https://api.github.com/repos/jhuckaby/Cronicle/releases/latest -s | jq .tag_name -r ||  0.9.51
  PYTHON_TAG: 3.11-bookworm

tasks:
  default:
    cmds:
      - echo "Image Registry {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:{{.CRONICLE_VERSION}}"
      - task --list-all
    silent: true

  docker-update:
    - task docker-build docker-push

  docker-build:
    dir: docker
    cmds:
      - ./entrypoint/gen_config.py > config/plugins.pixl
      - defer: rm -f config/plugins.pixl
      - docker pull docker:latest
      - |
        docker build --network=host \
        --build-arg CRONICLE_VERSION={{.CRONICLE_VERSION}} \
        -f docker.Dockerfile \
        -t {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:{{.CRONICLE_VERSION}} \
        .
  docker-scan:
    - docker scan {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:{{.CRONICLE_VERSION}}

  docker-push:
    - docker tag {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:{{.CRONICLE_VERSION}} {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:latest
    - docker push {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:{{.CRONICLE_VERSION}}
    - docker push {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:latest


  copy-plugins:
    - chmod +x ./plugins/*
    - sudo cp ./plugins/* /var/cronicle/plugins