# ENV required
# --------------------------------------------
# SERVICE_NAME=filesharing
# DOMAIN=localhost
# BASE_URL=/files
# VOLUME_MOUNT=files-data
# PUID=1000
# PGID=1000
# --------------------------------------------
# END ENV

version: "3.8"
services:
  apifiles:
    image: attap0n/apifiles:latest
    environment:
      TZ: Asia/Bangkok
    command: /app/apifiles serv --port 8080 --prefix "${BASE_URL}/files/" --dirpath "/data/public" -b
    user: ${PUID}:${PGID} # default: 1000 (required premission directory)
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}_apifiles.tls=true"
        - "traefik.http.routers.${SERVICE_NAME}_apifiles.entrypoints=web,websecure"
        - "traefik.http.routers.${SERVICE_NAME}_apifiles.rule=Host(`${DOMAIN}`) && PathPrefix(`${BASE_URL}/files`)"
        - "traefik.http.services.${SERVICE_NAME}_apifiles.loadbalancer.server.port=8080"
    networks:
      - proxy
    volumes:
      - ${VOLUME_MOUNT}:/data:ro

  filebrowser:
    image: filebrowser/filebrowser:latest
    environment:
      TZ: Asia/Bangkok
      PUID: ${PUID}
      PGID: ${PGID}
      # user: admin:admin
    command: --baseurl "${BASE_URL:-/files}/filebrowser" --database "/srv/.filebrowser.db"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}_filebrowser.tls=true"
        - "traefik.http.routers.${SERVICE_NAME}_filebrowser.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE_NAME}_filebrowser.rule=Host(`${DOMAIN}`) && PathPrefix(`${BASE_URL}/filebrowser`)"
        - "traefik.http.services.${SERVICE_NAME}_filebrowser.loadbalancer.server.port=80"
    networks:
      - proxy
    volumes:
      - ${VOLUME_MOUNT}:/srv

networks:
  proxy:
    external: true

volumes:
  files-data:
