# ENV required
# --------------------------------------------
# SERVICE_NAME=filebrowser1234
# DOMAIN=localhost
# BASE_URL=/filebrowser4321
# USERNAME=admin
# PASSWORD=admin
# VOLUME_MOUNT=/home/user
# PUID=1000
# PGID=1000
# --------------------------------------------
# END ENV
version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    environment:
      TZ: Asia/Bangkok
      PUID: 1000
      PGID: 1000
      # user: admin:admin
    command: --baseurl "${BASE_URL:-/files}"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.tls=true"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`) && PathPrefix(`${BASE_URL}`)"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
    networks:
      - proxy
    volumes:
      - ${VOLUME_MOUNT}:/srv

networks:
  proxy:
    external: true
