# ENV required
# --------------------------------------------
# SERVICE_NAME=filebrowser1234
# DOMAIN=localhost
# BASE_URL=/filebrowser4321
# VOLUME_MOUNT=/home/user
# PUID=1000
# PGID=1000
# --------------------------------------------
# END ENV
version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    environment:
      TZ: Asia/Bangkok
      PUID: ${PUID}
      PGID: ${PGID}
      # user: admin:admin
    command: --baseurl "${BASE_URL:-/files}" --database "/srv/.filebrowser.db"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}.tls=true"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`) && PathPrefix(`${BASE_URL}`)"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
    networks:
      - proxy
    volumes:
      - files-data:/srv

networks:
  proxy:
    external: true
volumes:
  files-data:
