version: "3.8"

services:
  sidekick-console:
    image: minio/sidekick:latest
    command: -q--health-path=/minio/health/ready --address ":9091" --cert /certs/cert.pem --key /certs/key.pem "http://minio1:9091"
    environment:
      TZ: Asia/Bangkok
    ports:
      - "9091:9091"
    networks:
      - minio
    volumes:
      - /etc/certs:/certs
  sidekick-api:
    image: minio/sidekick:latest
    hostname: sidekick-api
    command: -q--health-path=/minio/health/ready --address ":9090" --cert /certs/cert.pem --key /certs/key.pem "http://minio1:9090"
    environment:
      TZ: Asia/Bangkok
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    networks:
      - minio
    volumes:
      - ./etc/certs:/certs
  minio1:
    image: quay.io/minio/minio:latest
    hostname: minio1

    environment:
      TZ: Asia/Bangkok
      MINIO_VOLUMES: "/data1"
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
      MINIO_SERVER_URL: "https://localhost:9090"
      MINIO_BROWSER_REDIRECT_URL: "https://localhost:9091"
      MINIO_BROWSER_SESSION_DURATION: 6h
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_JOB_ID: minio-job
    command: minio server --console-address ":9091" --address ":9090"
    networks:
      - minio
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - minio-data:/data1
      - /etc/timezone:/etc/timezone:ro

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    environment:
      TZ: Asia/Bangkok
    volumes:
      - prometheus-data:/prometheus
    networks:
      - minio
    configs:
      - source: minio_prometheus
        target: /etc/prometheus/prometheus.yml

networks:
  minio:
volumes:
  minio-data:
  prometheus-data:
configs:
  minio_prometheus: # set data in docker config
    external: true
