# https://taskfile.dev

version: "3"

vars:
  DOCKER_REGISTRY: attap0n
  DOCKER_IMAGE: n8n
  DOCKER_TAG: latest
  N8N_VERSION: latest

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  docker-build:
    cmds:
      - docker pull n8nio/n8n:{{.N8N_VERSION}}
      - docker build --build-arg N8N_VERSION={{.N8N_VERSION}} -t {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:{{.DOCKER_TAG}} -f ./docker/Dockerfile .

  docker-push:
    - docker push {{.DOCKER_REGISTRY}}/{{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}
