# ----- ENV -------
# HOSTNAME=localhost
# PREFIX_PATH=/auth
# DB_USERNAME=keycloak
# DB_PASSWORD=keycloak
# DB_NAME=keycloak
# ADMIN_USER=admin
# ADMIN_PASS=admin
# ------ END ENV -------

version: "3.8"
services:
  keycloak-server:
    image: attap0n/keycloak:latest
    hostname: keycloak-server
    environment:
      TZ: Asia/Bangkok
      KC_DB_URL: "jdbc:postgresql://postgres_keycloak:5432/${DB_NAME:-keycloak}?characterEncoding=UTF-8"
      KC_DB: postgres
      KC_DB_USERNAME: ${DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${DB_PASSWORD:-keycloak}
      KEYCLOAK_ADMIN: ${ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASS:-admin}
      KC_HOSTNAME_URL: http://${DOMAIN:-localhost:8080}/auth
      KC_HTTP_RELATIVE_PATH: /auth
    command:
      - start
      - --proxy=edge
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - keycloak

  postgres_keycloak:
    image: "postgres:15"
    hostname: postgres_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Bangkok
      POSTGRES_USER: ${DB_USERNAME:-keycloak}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-keycloak}
      POSTGRES_DB: ${DB_NAME:-keycloak}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - keycloak

networks:
  keycloak:

volumes:
  postgres_data:
