# https://taskfile.dev

version: "3"

vars:
  DOCKER_REGISRTY: attap0n
  DOCKER_IMAGE: keycloak
  KEYCLAOAK_VERSION:
    sh: curl https://api.github.com/repos/keycloak/keycloak/releases/latest -s | jq .name -r || 25.0.2
  DOCKER_TAG: {{.KEYCLAOAK_VERSION}}
    

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  dev:
    cmds:
      - |
        docker run --rm \
        -p 8888:8888 \
        -e KEYCLOAK_ADMIN=admin \
        -e KEYCLOAK_ADMIN_PASSWORD=admin \
        -e KC_HOSTNAME_URL=http://localhost:8888/auth \
        -e KC_HTTP_ENABLED=true \
        -e KC_HTTP_PORT=8888 \
        {{.DOCKER_REGISRTY}}/{{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}  start

  docker-update:
    - task docker-pull docker-build docker-push
  build:
    - task docker-build

  docker-pull:
    - docker pull quay.io/keycloak/keycloak:{{.DOCKER_TAG}}

  docker-build:
    - |
      docker build \
      --build-arg=DOCKER_TAG={{.DOCKER_TAG}} \
      --build-arg=PREFIX=/auth \
      -t {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}} .

  tag:
    - docker tag {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}} {{.DOCKER_REGISRTY}}/{{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}
    - docker tag {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}} {{.DOCKER_REGISRTY}}/{{.DOCKER_IMAGE}}:latest

  docker-push:
    - task tag
    - docker push {{.DOCKER_REGISRTY}}/{{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}
    - docker push {{.DOCKER_REGISRTY}}/{{.DOCKER_IMAGE}}:latest
