# https://taskfile.dev

version: "3"

vars:
  IMAGE_REGISTRY: "indev.moph.go.th:5000"
  AIRFLOW_VERSION: 2.7.0-python3.11
  FILEBROWSER_VERSION: latest

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  up:
    cmds:
      - docker compose up -d
      # - docker compose --profile flower up -d

  logs:
    cmds:
      - docker compose logs -f

  down:
    cmds:
      - docker compose down
      - docker compose --profile flower down
  push:
    - docker push "{{.IMAGE_REGISTRY}}/airflow:{{.AIRFLOW_VERSION}}"
    - docker push "{{.IMAGE_REGISTRY}}/airflow-filebrowser:{{.FILEBROWSER_VERSION}}"

  build:
    - task airflow-build filebrowser-build

  airflow-build:
    cmds:
      - docker build --build-arg="AIRFLOW_VERSION={{.AIRFLOW_VERSION}}" -t "{{.IMAGE_REGISTRY}}/airflow:{{.AIRFLOW_VERSION}}" .

  filebrowser-build:
    - docker build --build-arg="FILEBROWSER_VERSION={{.FILEBROWSER_VERSION}}" -f Dockerfile-filebrowser -t {{.IMAGE_REGISTRY}}/airflow-filebrowser:{{.FILEBROWSER_VERSION}} .
