# https://taskfile.dev

version: "3"

vars:
  REGISTRY_NAME:
    sh: test -f registry.txt && cat registry.txt || echo "attap0n"
  HUB_IMAGE: jupyterhub-keycloak:latest
  LAB_IMAGE: jupyterlab:latest

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  t:
    - echo "{{.REGISTRY_NAME}}"

  stack:
    - docker stack deploy -c {{.STACK_FILE}} jupyterhub
  exec:
    - docker service exec jupyterhub_jupyterhub sh
  rm:
    - docker stack rm jupyterhub

  logf:
    - docker service logs -f jupyterhub_jupyterhub

  build:
    - task build-jupyterhub build-jupyterlab

  build-jupyterhub:
    dir: jupyterhub
    cmds:
      - docker build -t {{.HUB_IMAGE}} .

  build-jupyterlab:
    dir: jupyterlab
    cmds:
      - docker build -t {{.LAB_IMAGE}} .
  tag:
    - docker tag {{.HUB_IMAGE}} {{.REGISTRY_NAME}}/{{.HUB_IMAGE}}
    - docker tag {{.LAB_IMAGE}} {{.REGISTRY_NAME}}/{{.LAB_IMAGE}}

  push:
    - task tag
    - docker push {{.REGISTRY_NAME}}/{{.HUB_IMAGE}}
    - docker push {{.REGISTRY_NAME}}/{{.LAB_IMAGE}}
