version: "3.9"
services:
  vertica-ce:
    image: attap0n/vertica-ce:latest
    environment:
      APP_DB_USER: "dbadmin"
      APP_DB_PASSWORD: "vertica"
      TZ: "Asia/Bangkok"
    entrypoint: ["/bin/bash", "-c", "verticactl"]
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - ./tmp/data:/data

  vertica-mc:
    image: attap0n/vertica-ce:latest
    entrypoint: ["/bin/bash", "-c", "mcctl"]
    environment:
      TZ: "Asia/Bangkok"
    ports:
      - "5450:5450"
    volumes:
      - ./tmp/home:/home/dbadmin
