# https://taskfile.dev

version: "3"

vars:
  DOCKER_REGISTRY:
    sh: (source .env && echo "${REGISTRY:-attap0n}") || echo "attap0n"
  PROJECT_NAME: "vertica-ce"
  VERSION: "24.1.0-0"

tasks:
  default:
    cmds:
      - echo "Image Registry {{.DOCKER_REGISTRY}}/{{.PROJECT_NAME}}:{{.VERSION}}"
      - task --list-all
    silent: true

  dev:
    - docker compose up -d
    - docker compose logs -f
  down:
    - docker compose down

  docker-update:
    - task docker-build docker-tag docker-push

  docker-build-mc:
    aliases:
      - dbmc
    cmds:
      - |
        docker build \
        --network=host \
        -f MC.Dockerfile \
        --build-arg VERSION={{.VERSION}} \
        -t {{.DOCKER_REGISTRY}}/vertica-ce-mc:{{.VERSION}} .
      - |
        read -p "Push image? [y/N] " IS_OK
        test "$IS_OK" = "y" && task docker-push-mc
  docker-build:
    cmds:
      - |
        docker build \
        --network=host \
        --build-arg VERSION={{.VERSION}} \
        -t {{.DOCKER_REGISTRY}}/vertica-ce:{{.VERSION}} .
      - |
        read -p "Push image? [y/N] " IS_OK test "$IS_OK" = "y" \
        && task docker-push

  docker-tag:
    - docker tag {{.DOCKER_REGISTRY}}/vertica-ce:{{.VERSION}} {{.DOCKER_REGISTRY}}/{{.PROJECT_NAME}}:{{.VERSION}}

  docker-push-mc:
    - docker push {{.DOCKER_REGISTRY}}/vertica-ce-mc:{{.VERSION}}

  docker-push:
    - docker tag {{.DOCKER_REGISTRY}}/vertica-ce:{{.VERSION}} attap0n/vertica-ce:latest
    - docker push {{.DOCKER_REGISTRY}}/{{.PROJECT_NAME}}:{{.VERSION}}
    - docker push {{.DOCKER_REGISTRY}}/vertica-ce:latest

  docker-stack:
    - (docker stack rm vertica && sleep 10s) || echo "not running"
    - docker stack deploy -c vertica-stack.yml vertica
