version: "3.9"
services:
  vertica:
    image: vertica/vertica-ce:latest
    environment:
      APP_DB_USER: "dbadmin"
      APP_DB_PASSWORD: "vertica"
      TZ: "Asia/Bangkok"
    ports:
      - "5433:5433"
      - "5444:5444"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data2
        target: /data
volumes:
  vertica-data2:
